### ISSUE TITLE
Recommended Plugins in sidebar-right.php

### ISSUE THREAD

**Issue by kniebremser** [Frumph/easel#25]
Would not that be a good place for the last remote recommended plugins?
easel-companion is unavailable and in WP 3.9 is also the audio / video support better

**Comment by kniebremser** [comment]
Can we update the plugins, they are partially out of date.

**Comment by Frumph** [comment]
absolutely

**Comment by Frumph** [comment]
Can even get rid of recommended comment too and just post the info about widgets need to be added here

**Comment by kniebremser** [comment]
In all cases  plugin "broken link checker" to add.

**Comment by Frumph** [comment]
broken link checker is broken ;/  it says 403 redirects to be broken ;/

**Comment by Frumph** [comment]
i have it on frumph.net and it constantly sends me emails on links that work but it says are broken

**Comment by kniebremser** [comment]
For me it works without error.

**Comment by kniebremser** [comment]
ComicPress to Comic Easel Migrator?

**Comment by kniebremser** [comment]
TinyMCE Visual Editor To The Comment Form ?
https://wordpress.org/plugins/tinymce-visual-editor-comment/

**Comment by Frumph** [comment]
oh uhm, not fond of that (the tinymce for comments) because it adds a huge overhead on load times

**Comment by kniebremser** [comment]
for easel completely remove Recommended plugins?

and for ComicPress rename in Recommended Comic Plugins with links for comic easel plugin and the migrations plugin?

**Comment by Frumph** [comment]
I don't think those are entirely necessary anymore really,  they originally were there just as filler space to begin with so it didn't look so empty ;/

Want to spend some time chatting via messenger or something and have a programming session on prepping for release?  Gotta do it soon to fix the /release/ the fix for the customizer problem that happened with 4.1 release.

**Comment by kniebremser** [comment]
Yes we can chat via messenger. Which messenger do you use?

**Comment by Frumph** [comment]
Primarily facebook http://facebook.com/philip.hofer but also have skype "Frumph"

**Comment by kniebremser** [comment]
Oki doki. Via "Skype" My nickname is fluchtsportler

**Comment by Frumph** [comment]
found someone with that name via skype sent them a add to contacts, hope that's you
