### ISSUE TITLE
better display for blognav for the schema "mecha"

### ISSUE THREAD

**Issue by kniebremser** [Frumph/easel#26]
blognav-prev and blognav-next stick of the edge
With the following changes it looks better:
.blognav-prev {
    margin-left: 10px !important;
}

.blognav-next {
    margin-right: 10px !important;
}
before:
![before](https://f.cloud.github.com/assets/4800726/2440650/db7f48a6-ae09-11e3-9c40-7e5eb82fe021.PNG)
after:
![after](https://f.cloud.github.com/assets/4800726/2440706/acf0b10e-ae0a-11e3-86dd-6f60b20ac8bc.PNG)

**Comment by kniebremser** [comment]
I added a small pixel change for the schematic mecha in the css.

body.scheme-mecha-.blognav prev {
     margin-left: 5px;
}

body.scheme-mechanical .blognav-next {
     margin-right: 5px;
}

The two entries thus no longer stick to the edge. see picture
![blognav](https://cloud.githubusercontent.com/assets/4800726/5721845/a4fad7ee-9b36-11e4-80b2-401cb522b41c.PNG)
left entry without change
right entry with change

The change only affects mecha, since blognav has a different background color.

**Comment by Frumph** [comment]
ok
